version: '3.8'

services:
  devcontainer:
    container_name: PythonDevcontainer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.11"
    network_mode: host
    volumes:
      # Mount the local directory into the container
      - ..:/workspace:cached
    env_file:
      - ".env"
    command: sleep infinity # Keep the container running

volumes:
